### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined when clicking on live_patch

### ISSUE THREAD

**Issue by ccapndave** [phoenixframework/phoenix_live_view#1144]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.0
* NodeJS version (node -v): 12.18.0
* NPM version (npm -v): 6.14.4
* Operating system: MacOS 10.14.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a UI with various `live_patch`s.  If I click first on `live_patch` A, then I get this error:

```
phoenix_live_view.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
eval @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
eval @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
eval @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
eval @ phoenix_live_view.js:1
eval @ phoenix_live_view.js:1
eval @ phoenix.js:1
value @ phoenix.js:1
eval @ phoenix.js:1
value @ phoenix.js:1
eval @ phoenix.js:1
value @ phoenix.js:1
eval @ phoenix.js:1
decode @ phoenix.js:1
value @ phoenix.js:1
conn.conn.onmessage @ phoenix.js:1
Show 26 more frames
phoenix_live_view.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
```

which is coming from:

```
            {
                key: "toOutputBuffer",
                value: function(e, t) {
                    if (e.d)
                        return this.comprehensionToBuffer(e, t);
                    var n = e.s;
                    t.buffer += n[0]; // <-- ERROR
                    for (var i = 1; i < n.length; i++)
                        this.dynamicToBuffer(e[i - 1], t),
                        t.buffer += n[i]
                }
            }
```

Clicking anything other `live_patch` also throws the same error from then on.

However, if I click first on `live_patch` B then I don’t get the error and everything works normally (including clicking on `live_patch` A)!

Refreshing the page keeps the same behaviour - if its was working it keeps working, if it was broken then it stays broken.  Navigating away from the page and back again appears to "reset" the behaviour, and the original rules of what I click first re-apply.

I've tried this on all different versions and the issue was definitely introduced in 0.14.0 (i.e. it works normally up to 0.13.3).

I can reproduce this reliably, so if there is anything else I can do to help locate the problem let me know.

**Comment by josevalim** [comment]
Hi @ccapndave, thanks for the report! To be clear, it was introduced in v0.14.0 but still exists on v0.14.4, right? If you can isolate this error, then it would be extremely helpful to help us address it, especially as it may be a server problem.

**Comment by ccapndave** [comment]
Yes, I first noticed it on 0.14.4.  I would love to help, but I have a deadline approaching so I'm afraid I can't do a general investigation right now.  But if there are any specific steps you would like me to do that would be no problem.

**Comment by josevalim** [comment]
I will close this for now. if you have a mechanism to reproduce it, please let us know!

**Comment by ccapndave** [comment]
Just to let you know that this issue still exists in 0.15.3.  Its so weird that I'm the only person getting this!

**Comment by ccapndave** [comment]
I've spent a long time trying to make a minimal reproducible case I can share, but I'm afraid I can't manage to make one.

However, I've tracked the problem down to a particular stateless nested live component which looks like this:

```
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>">
      <%= if @show_selectors do %>
        <div phx-click="change_mode" phx-target="<%= @phx_target %>" phx-value-mode="select">Select</div>
      <% end %>
    </div>
    """
  end
```

This is where things get strange.

 - If `@show_selectors` evaluates to `true`, the error occurs
 - If `@show_selectors` evaluated for `false`, the error doesn't occur
 - However, if I replace `@show_selectors` with `true` or `false`, the error never occurs

Leaving `@show_selectors` as `true` (so the error occurs) I can *also* fix it by removing `phx-target`.

This is a bit of showstopper for us upgrading so if there is anything at all I can do to help fix this please let me know.  I can reproduce it every single time on our project.

**Comment by josevalim** [comment]
Reopening! Although we definitely need a complete way to reproduce (i.e. a sample app or a fuill set of LiveViews).

**Comment by ccapndave** [comment]
I can see about organising to give you access to the full repository, but I'm afraid it couldn't be publicly accessible.  Would that work?

**Comment by josevalim** [comment]
I will be honest and say we have very limited time and we need to optimize it. If you can't isolate it, then it means we would have to isolate it, and we have other areas to focus on. So thanks for the offer but that wouldn't work, sorry. :(

**Comment by ccapndave** [comment]
Understood :)  I've worked around it for the moment by using CSS classes instead of conditionals to show and hide the bits in this component, but if the issue rears it head again I'll have another go at reproducing the bug.

**Comment by rogelio2k** [comment]
![image](https://user-images.githubusercontent.com/113741/104962964-53388680-59b8-11eb-9479-fd7ce43d9e7b.png)

I think I ran into the same issue, using 0.15.3, I click in any `live_patch` and some `live_redirect` (these trigger the error but I don't know if they are actually the issue here) and the view loads fine but it doesn't leave the loading state and a JS error is shown on the console (see screenshot). I will complement this comment if I have further information.

**Comment by rogelio2k** [comment]
I removed my latest comment - fixed the issue by:

1) Adding missing DOM id on the element that was calling a ph-hook
2) Remove `node_modules/` and run `npm install`

**Comment by ccapndave** [comment]
I'm very certain that I've done both these steps, but just to be 110% sure I'll do them again and confirm I can still reproduce.

**Comment by Ninigi** [comment]
We have been getting this error after upgrading from 0.14.8 to 0.15.x

After scratching my head for a few hours, I realized that the `live_render` behaviour for (child ?) LVs seems to have changed: it used to be that, once mounted, the only way of remounting the LV was changing the id - after the upgrade they remounted every time the session changed.

so in the parent LV, if you had something like this

```elixir
def render(assigns) do
  ~L"""
   <%= live_render(@socket, OtherLiveView, id: :other_lv, session: %{parent_params: @params}) %>
   """
 end
 ```

it would mount once, and remain in its own state, even if `@params` changed - now it remounts if `@params` is marked as dirty.

This was a problem for our app in itself, because everything was geared towards LVs only mounting once and then use broadcasts/`send` to update each other, so we fixed that using `phx-update="ignore"` (don't forget to give the DOM element you put this on an ID).
And suddenly this Javascript error did not show up anymore.

My theory - completely shooting from my hip here - is that liveview is sending DOM updates for the LV that will be remounted because of the change, and there is some kind of race condition, resulting in the element which the update should be applied to not being there anymore (??)

I'll try and put together a simple example to reproduce this issue - but the app we encountered this in is fairly complex, and I am not sure it can be reproduced in a simple way.

**Comment by Ninigi** [comment]
@ccapndave Is the app you are experiencing this issue in using child liveviews?

**Comment by ccapndave** [comment]
@Ninigi Mostly I use the top level router `live` macro, with everything else being live components, but there are a few child live views in there (for stuff that shouldn't bring down the page if it crashes).  However, I just did a test where I removed the only child live view on the particular page with this problem, and the crash still happens.

**Comment by ccapndave** [comment]
@rogelio2k I can also confirm that all my hooks have an id, and that clearing `node_modules` doesn't fix the issue.

**Comment by jonatanklosko** [comment]
I run into this and managed to create a minimal reproducible case [here](https://github.com/jonatanklosko/bug_report_lv_1144/tree/master/lib/missing_static_web/live).

The example shows a list of items one of which can be selected. Initially there's one item and it's selected, so for [this conditional](https://github.com/jonatanklosko/bug_report_lv_1144/blob/1606d631d94faa6d94c6bb80f866191dc775b859/lib/missing_static_web/live/item_component.ex#L9-L11) the following gets sent (correctly):

```js
{ 0: "true", s: ["\n    (Is selected is \"", "\")\n  "] }
```

Now when we insert a new item and make it selected, the corresponding data sent is this:

```js
{ 0: "true" }
```

The `static` part is missing and that causes [this](https://github.com/phoenixframework/phoenix_live_view/blob/b9e2e8ea7a22fc30e88e6eae2e3958dbeed1b57d/assets/js/phoenix_live_view.js#L548) to error.

**Comment by sb8244** [comment]
@josevalim I'm not sure if it's related to this fix, but I am getting the same error regarding `statics is undefined`. I am working very hard to trace through the actual issue, but struggling hard. Somehow, `static` is undefined at line https://github.com/phoenixframework/phoenix_live_view/blob/v0.15.7/assets/js/phoenix_live_view.js#L588

Reproduction probably won't be super possible for me, this is a very complex recursive form that I'm working through.

**Comment by josevalim** [comment]
Yeah, maybe there are still bugs in specific situations but I would need a mechanism to reproduce it. :( If you want, I will be glad to do pairing early morning tomorrow or friday. Send me an email (it is on my GH profile). :)
