### ISSUE TITLE
auto_upload behavior and usage

### ISSUE THREAD

**Issue by marcelfahle** [phoenixframework/phoenix_live_view#1225]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.6
* Phoenix LiveView version (mix deps): 0.15.0-dev (current master)
* NodeJS version (node -v): 12.18.3
* NPM version (npm -v): 6.14.6
* Operating system: macOS 10.15.7
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, FF
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have two issues with `auto_upload` (when using it with straight to S3 uploads)

1. If I use `auto_upload: true` the consumption of files **during** `progress` is absolutely necessary. The docs currently say 
> you **can** pair `auto_upload: true` with a custom progress function

But if I don't do this, the submit callback never gets fired. The form is frozen, and execution is stuck [here](https://github.com/phoenixframework/phoenix_live_view/blob/b87e5f829168911bb43d5bce6eb75847ed9e3bbd/assets/js/phoenix_live_view.js#L2695) (_has uploads in progress_) without warning.

So currently, there is no way for me to consume auto_uploaded files on submit. 

But while consumption during progress works great, the reason I was trying to do it on submit is my next issue:

2. Once files get consumed, they won't be shown anymore in `live_img_preview`. This is most definitely by design, but because of problem 1, I currently have to assign my uploaded file to a separate field on the socket, so I can display it, which feels a bit dirty.

I used @mcrumm 's [example](https://github.com/mcrumm/live_upload_example) to whip up a quick project that shows the issues real quick, which you can find [here](https://github.com/marcelfahle/live_upload_example) (and to make sure it not only happens in my actual project, which is of course more complex).
Just fill out the `config/dev.secret-example.exs` (and rename obvi) with some valid S3 stuff and see what happens when [we remove the custom progress function](https://github.com/marcelfahle/live_upload_example/blob/f1a238695371faceac8e248ffda4b301927088ea/lib/drops_web/live/page_live.ex#L13). 

Anyway, all of this might be totally me not using unreleased features correctly, and if so, I apologize for wasting time 😬 ; I thought I make sure you guys are aware of it.

### Expected behavior

I got it working now, but I find the silent form freeze not optimal. If it's by design, we then should at least change the docs or return a warning to the user.  What do you think? 🙂

**Comment by chrismccord** [comment]
I believe this is fixed on master. Thanks!

**Comment by LostKobrakai** [comment]
I'm still observing the behaviour of `auto_upload` getting stuck on submit with 0.15.0.

**Comment by chrismccord** [comment]
@LostKobrakai are you observing this with the steps provided above, or in your own code/scenario. If not a recreation of above, can you please open an new issue with new code that recreates? Thanks!

**Comment by LostKobrakai** [comment]
I also do direct to S3 uploads with `auto_upload: true`. When I hit submit the button does change (`phx_disable_with`), but on the websocket connection I don't see the `save` event being pushed. So this very much feels like the same issue.

**Comment by marcelfahle** [comment]
I just upgraded my example to the latest versions and it still persists.

**Comment by plicjo** [comment]
@chrismccord Confirmed just now that this issue is still around.

**Comment by chrismccord** [comment]
Please give master a try folks and let me know how it looks. Thanks!

**Comment by mcrumm** [comment]
@chrismccord Looks good to me! 🔥

**Comment by marcelfahle** [comment]
Yes, same here, not stuck anymore. Thank you Chris! 🔥 🙏
