### ISSUE TITLE
A push_redirect/2 related LiveView JS bug or something else?

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#1520]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.9
* Phoenix LiveView version (mix deps): 0.15.7
* NodeJS version (node -v): 12.14.1
* NPM version (npm -v): 6.13.4
* Operating system: Linux Mint
* Browsers you attempted to reproduce this bug on (the more the merrier): FF, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Before moving to reproduce this in a sample app, I need to know whether this is a known problem and if it is me who's doing something conceptually wrong.

I have several LiveView instances in a single root template, say X, C, Foo and Bar. X and C are rendered with live_render/3 while Foo and Bar are mutually exclusive and rendered as <%= @inner_content %>, thus Foo and Bar have access to params via handle_params (as intended) while X and C do not.

X's behavior is independent of other LiveView instances while C controls the toggling b/w Foo and Bar by broadcasting the events Foo and Bar have subscribed to. Toggling between the two is done by calling push_redirect/2 and a message gets sent back to C so that it can assign the status change that it renders in its own template.

The problem boils down to push_redirect/2 effectively disabling the client-side updates of both X and C when and if they occur during the client-side push_redirect update. Since C is directly related to Foo and Bar in terms of rendering the toggle status, it is the easiest to demonstrate the problem. The C's template itself is rendered (as I output the single assigned value that is changing in the template) and even debugging log in the browser's console shows it arrives, but the LiveView JS client makes no changes to the C's DOM. On the other hand, if sending the event to C is delayed by say 1000 ms (with Process.send_after/4), which is enough time for the push_redirect to be fully applied, then the C's changes manage to get applied on the client side.

With the independent X LiveView instance, the problem is very similar. Even if there is no communication between its process and Foo or Bar, its periodical, independently timed updates simply cease to be reflected in the client-side updates if they once happen to overlap with a Foo's or Bar's push_redirect update while the messages from the server keep on coming as shown in the web console log. An indicative side effect is that X restores its client-side updating once the user switches to another window and back to the browser.

**Comment by josevalim** [comment]
If C is rendered **outside** of Foo and Bar, then by your description, it _sounds to me_ it is a bug.

**Comment by DaTrader** [comment]
Yes, C is rendering its own HTML outside of the Foo and Bar. None of the LiveViews is nested.

**Comment by josevalim** [comment]
I see. Isolating it sounds like a logical next step to me but you may also wait to see the opinion of others. :)

**Comment by DaTrader** [comment]
The soonest I can try to isolate it is this weekend, so let's hear them out. And I'd also like to hear if Chris has any ideas.

**Comment by chrismccord** [comment]
Please verify that C is rendered *outside* of the live layout, ie in the root template. If it’s within a live layout the it will actually live inside the routed LV

**Comment by DaTrader** [comment]
Ok. Here's an isolated app demonstrating the issue. Try clicking first on "Show Foo" then "Show Bar" and thus in circles and you will notice that the message "Clicked:" in the switchboard (LiveView C) above is not changing regularly if ever. It may change from time to time but generally it doesn't (and it should).

https://github.com/DaTrader/cards_demo2

In the SwitchLive LiveView module please uncomment the line #90 and comment the #91 and it should work (as originally described in my issue report).

**Comment by mveytsman** [comment]
I was able to reproduce this issue with the following app: https://gist.github.com/mveytsman/03e68c56be33af892be42e4bf18714ce

We're indeed not rendering an update in a second liveview in the root template if it's sent right after a redirect.

The good news is when I upgraded to LiveView master (tested at https://github.com/phoenixframework/phoenix_live_view/commit/2e40f7fd808664f5bc22f09287155d4016076054) the problem went away.

@DaTrader can you confirm if this is the case for your more complicated example?
@chrismccord Should I dig in to try to find out the root-cause to backport a change, or are we comfortable having this being fixed in 0.16.0 forward?

**Comment by DaTrader** [comment]
@mveytsman 

If I change my LiveView dependency to its master on github, I get all sorts of diverged dependencies re phoenix_html and live_dashboard.

Could you please share your mix dependencies as a whole?

**Comment by josevalim** [comment]
Set both phoenix_html and phoenix_live_view to master and also pass `override: true`.

**Comment by DaTrader** [comment]
I upgraded both the demo app and my actual app to the 0.16.0 master and the originally reported issue is still there..

If required, I can upload the 0.16.0 version of the cards_demo for I had to change the router.ex code which no longer takes session for a live route option and a number of other things, and eventually I managed to run it.

However, because of the breaking changes in 0.16.0 I humbly suggest sticking to 0.15.7 for tracing this bug.

**Comment by chrismccord** [comment]
Assuming this is fixed in 0.16 then we won’t backport. @DaTrader it’s difficult to tell in your example where the flow is since there is a lot going on with the switch assign. Would it be possible to simply? Thanks!

**Comment by DaTrader** [comment]
Ok. Let's go step by step.

1. The bug is not fixed in 0.16. That was a @mveytsman's assumption based on another example that he found similar, but it turned out was not similar enough.

2. Again, if required for debugging on LV 0.16, I can upload a cards_demo2 version that works with LV 0.16 for you to see that 1) stands and so you don't need to spend your time changing the demo to adjust for the breaking changes in 0.16.

3. @chrismccord Please note that the SwitchLive LiveView (the one in question for demonstrating the existence of the bug) only has a single assign and there's virtually nothing else going on in it except for handling the info received by the Foo and Bar liveviews after they push_redirect/2. 

Re assign complexity, I guess you're referring to DeckLive (the one with LiveViewX message on the screen) and yes, there is a lot going on there indeed, but you can remove this LiveView from the root template altogether and the bug with the push_redirect/2 and send() to SwitchLive will still be there. 

The reason why I included the DeckLive (LiveViewX) in the first place was to demonstrate how grave it is when the bug gets to it. As previously described, this LiveView does not even communicate to the other three LiveViews, it just runs on its own. But, when the bug (of not applying the changes in JS after push_redirect/2) starts affecting it, all of its appended containers tend to collapse to a single item. This has never happened to me throughout the past two years, but it happens when the push_redirect/2 related JS bug begins skipping updates.

Thanks

**Comment by josevalim** [comment]
> Again, if required for debugging on LV 0.16, I can upload a cards_demo2 version that works with LV 0.16

Yes, running it against master would be helpful, because the fix will be done against master anyway.

My understanding is that the code does this:

1. Switchboard broadcasts a message with self()
2. Another LiveView receives the broadcast, sends a message, and pushes a redirect
3. Switchboard receives the message and pushes updates (which are not being received)

There is a lot of indirection in the current code (such as proxy modules) to reproduce the behaviour and simplifying it further will help find out the root cause. :+1:

**Comment by DaTrader** [comment]
@josevalim 

Yes, that's what the code does. 

I'll now replace the module related indirections with the module names and upload the 0.16 version of the demo.

**Comment by DaTrader** [comment]
There it is. Same repo as before:

https://github.com/DaTrader/cards_demo2

**Comment by DaTrader** [comment]
@josevalim 

Pardon, re the point no. 3 in your summarizing the code: AFAIK, the updates get always received by the LV JS, as observable in the web console when debugging is enabled, but they don't get applied if after a push_redirect/2.

**Comment by chrismccord** [comment]
This should have been fixed in 0.17.9. Thanks!

**Comment by DaTrader** [comment]
@chrismccord 

I'm afraid it's not. I've migrated the cards_demo2 to to 0.17.9 (running on Erlang 24.3 and Elixir 1.13.4.) and it still features the same LV bug as originally reported,

Same repo as before: https://github.com/DaTrader/cards_demo2
