### ISSUE TITLE
Formatting and check-format are inconsistent

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix_live_view#3544]
on the current main branch of liveview I get this inconsistency:

On top it's the diff of the latest formatting and on the bottom the check-format

![image](https://github.com/user-attachments/assets/3b0e0967-28bf-45f2-9166-531951a7cc8f)

Manually chaning the code the following fixes it:

![image](https://github.com/user-attachments/assets/72314d3f-8811-4297-a126-ccd6507a02b3)

**Comment by SteffenDE** [comment]
@feliperenan can you have a look at this?

**Comment by josevalim** [comment]
Fixed in v1.0.1.

**Comment by ar7casper** [comment]
@josevalim I'm using `1.0.2` and I have a similar issue - 
```elixir
  def t2(assigns) do
    ~H/1"""
    <p class={[get_font_family(assigns), "text-[14px] leading-[20px] font-normal", @class]} {@rest}>
      {render_slot(@inner_block)}
    </p>
    """
  end
```

and it should be 
```elixir
  def t2(assigns) do
    ~H/1"""
    <p class={[get_font_family(assigns), "text-[14px] leading-[20px] font-normal", @class]} {@rest}>{render_slot(@inner_block)}</p>
    """
  end

```

the extra whitespace does funky stuff in the UI.

**Comment by SteffenDE** [comment]
@ar7casper do you really see an inconsistency between `mix format` and `mix format --check-formatted`? You can prevent the line break by setting the `phx-no-format` attribute on your p tag.

**Comment by ar7casper** [comment]
@SteffenDE adding `phx-no-format` on `p` worked.
Adding attributes to fix formatting issues seems a bit off.

**Comment by SteffenDE** [comment]
@ar7casper I‘m sorry, but I still cannot see a **formatting issue** here. You did not answer if you were indeed seeing an inconsistency between format and check-formatted (what this issues is about). The fact that the formatter adds newlines to block level elements when the line length is too long is how it’s always has been, and is clearly documented: 

> A block element will go to the next line, while inline elements will be kept in the current line as long as they fit within the configured line length.

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html#module-formatting

Since you’re using a `p` element, which is block level, you need to explicitly tell the formatter if you don’t want formatting with `phx-no-format`. How else should it know how to do its job in that case?

**Comment by ar7casper** [comment]
> How else should it know how to do its job in that case?
I have been in JS land for about 12 years and never had an issue with linter / prettier adding whitespace to the actual code.
These whitespaces shouldn't creep into the code.
There are several options - 
1. Don't add a whitespace when formatting. You can break the line without adding the whitespace.
2. Remove the whitespace during compilation (which, I believe, is an issue, cause how would you know if it's there intentionally or not)

Requiring the user to add attributes to cope with how the formatter works is a poor way of dealing with it.
The formatter should serve the code, not the other way around.

> You did not answer if you were indeed seeing an inconsistency between format and check-formatted
Didn't have a chance to check yet.

**Comment by ar7casper** [comment]
@SteffenDE 

The issue is not with the formatter breaking the line, the issue is that it adds whitespace while doing so -
The two spaces around the curly braces should be there.
![Image](https://github.com/user-attachments/assets/7188f175-fcd8-49dc-b81a-4b0f8dbd418b)

**Comment by tcoopman** [comment]
@ar7casper this is a different issue than the one described here. Please either open a new issue, or check if there is an issue like this already (for example #1985 seems similar)

**Comment by ar7casper** [comment]
@tcoopman I've created #3644 .
Thanks.
