### ISSUE TITLE
Error when a live update tries to render multiple sibling elements

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix_live_view#939]
I found that I got a javascript error when I had a live template that would inject two sibling <divs>'s inside of an if condition. A minimal example reproducing it and the stack trace is below.

### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): 10.19.0
* NPM version (npm -v): 6.13.4
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 76.0.1, Chromium 83.0.4103.61
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

I have the following template

```eex
<%= live_component @socket, MyComponent, id: :test_component %>

<div>Div outside component</div>
```

and the following Live Component

```ex
defmodule BikeBrigadeWeb.TaskLive.TestComponent do
  use BikeBrigadeWeb, :live_component

  @impl true
  def mount(socket) do
    {:ok, assign(socket, clicked: false)}
  end


  @impl true
  def handle_event("toggle_clicked", _params, socket) do
    {:noreply, assign(socket, clicked: !socket.assigns.clicked)}
  end

  @impl true
  @spec render(any) :: Phoenix.LiveView.Rendered.t()
  def render(assigns) do
    ~L"""
    <%= if @clicked  do %>
     <div>Selected: first div</div>
     <div>Selected: second div</div>
    <% else %>
      <div>Not clicked: only div</div>
    <% end %>
    <button phx-click="toggle_clicked" phx-target="<%= @myself %>">click!</button>
    """
  end
end
```

Upon initial page load, the html I see is
```html
<div data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-1">Not clicked: only div</div>
<button phx-click="toggle_clicked" phx-target="0" data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-3">click!</button>
<div>Div outside component</div>
```

When I click I see this

```html
<div data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-1">Selected: first div</div>
<div data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-3">Selected: second div</div>
<button phx-click="toggle_clicked" phx-target="0" data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-5">click!</button>
<div data-phx-skip=""></div>
```

The div that was outside the component has disappeared! Instead I seem to have gotten a new empty div with `data-phx-skip`

When I click again I see

```html
<div data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-1">Not clicked: only div</div>
<button phx-click="toggle_clicked" phx-target="0" data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-5" class="phx-click-loading" data-phx-ref="1">click!</button>
<div data-phx-skip=""></div>
<button phx-click="toggle_clicked" phx-target="0" data-phx-component="0" id="phx-FhPvBAfd45hGpwWD-0-3">click!</button>
```

Now the button has multiplied and I have two of them

I also got the following stack trace while doing this:
```
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at Object.isPhxUpdate (phoenix_live_view.js:1)
    at onBeforeNodeDiscarded (phoenix_live_view.js:1)
    at L (phoenix_live_view.js:1)
    at phoenix_live_view.js:1
    at phoenix_live_view.js:1
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at phoenix_live_view.js:1
isPhxUpdate @ phoenix_live_view.js:1
onBeforeNodeDiscarded @ phoenix_live_view.js:1
L @ phoenix_live_view.js:1
(anonymous) @ phoenix_live_view.js:1
(anonymous) @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
(anonymous) @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
value @ phoenix_live_view.js:1
(anonymous) @ phoenix_live_view.js:1
(anonymous) @ phoenix.js:1
value @ phoenix.js:1
(anonymous) @ phoenix.js:1
value @ phoenix.js:1
(anonymous) @ phoenix.js:1
value @ phoenix.js:1
(anonymous) @ phoenix.js:1
decode @ phoenix.js:1
value @ phoenix.js:1
conn.conn.onmessage @ phoenix.js:1
```

### Expected behavior

The initial render was correct. After clicking, I expected to see 
```html
 <div>Selected: first div</div>
 <div>Selected: second div</div>
 <button phx-click="toggle_clicked" phx-target="<%= @myself %>">click!</button>
<div>Div outside component</div>
```

After the second click I expected to go back to the initial state

```html
 <div>Not clicked: only div</div>
 <button phx-click="toggle_clicked" phx-target="<%= @myself %>">click!</button>
<div>Div outside component</div>
```

**Comment by mveytsman** [comment]
Is this because a live component expects everything in its template to be inside one element?

I made a working patch for `phoenix_live_view.js` that gets rid of the stack trace, but I will still lose the div that's below the component on updates

**Comment by josevalim** [comment]
This has been fixed IIRC. Please try latest LV and let us know if it works. Remember to remove assets/node_modules after updating.

**Comment by mveytsman** [comment]
Thanks for the super fast response as always Jose!!

I upgraded to `0.13.2` and while the exception is gone, but the div still disappears:

```
<%= live_component @socket, MyComponent, id: :test_component %>

<div>Div outside component</div> <--- this div disappears when the component is re-rerenderd
```

I think this is still a bug.

**Comment by mveytsman** [comment]
:bow: thanks @chrismccord !

**Comment by numair** [comment]
`% elixir -v
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]`

Hi @chrismccord , bad news... This is still happening, as of LiveView 0.18.2. I have a nested LiveComponent which is implemented using the <.live_component /> tag. When I web-inspect the LiveComponent div, I can sometimes see stale data and sometimes see no rendered content at all -- in which case there is a `data-phx-skip` tag instead of the content.

Maybe there was a bug that was re-introduced in the past few months? I don't think I had encountered this error when I wrote the original code about a year ago, but maybe I'm wrong. My workaround for now was to get rid of the nested LiveComponents and simply use standard Phoenix views. Maybe nesting LiveComponents is ill-advised, and it's not something that is meant to be done? Thanks for any advice you can lend to prevent future frustration.

**Comment by chrismccord** [comment]
We would need a reproducible example of the issue to be able to take a look. Thanks!

**Comment by numair** [comment]
I will try to make a sample project next week. Thanks for your quick feedback!
